BEGIN TRANSACTION;


CREATE TABLE temp_DBInfo_534011718
(
    Time NUMERIC,
    Id INTEGER,
    DevId INTEGER,
    PRIMARY KEY (Id)
);


INSERT INTO temp_DBInfo_534011718 (Time,Id,DevId) SELECT Time,Id,NULL AS DevId FROM DBInfo;

DROP TABLE DBInfo;
ALTER TABLE temp_DBInfo_534011718 RENAME TO DBInfo;

CREATE TABLE SequenceNumbers
(
    Name TEXT,
    Value INTEGER DEFAULT 1
);

COMMIT TRANSACTION;
